# icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[[block]]
block = "custom"
command = "spt playback --format"
interval = 3

[[block.click]]
button = "left"
cmd = "spt playback --toggle"

[[block]]
block = "custom"
command = "xrandr --listmonitors | tail -n+2 | tr '+' ' ' | cut -d' ' -f 4 | tr '\n' ' '"
interval = "once"
signal = 4

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
format = "$icon {$signal_strength $ssid |Wired connection} via $device"

# [[block]]
# block = "sound"
# on_click = "pulsemixer --toggle-mute"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "custom"
command = "sed 's/  //' <(curl 'https://wttr.in/?format=1' -s)"
interval = 600

[[block]]
block = "battery"
